export interface BlogArticle {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  date: string; // ISO date
  readingTime: number; // minutes
  category: string;
  image?: string;
}

export const blogArticles: BlogArticle[] = [
  {
    slug: "que-es-certificado-de-reciclaje",
    title: "Qué es un certificado de reciclaje y por qué tu empresa lo necesita en 2026",
    description:
      "Guía completa sobre el certificado de reciclaje en Chile: qué es, qué datos debe contener, para qué sirve en auditorías ambientales, ISO 14001 y Ley REP, y cómo obtenerlo de forma digital.",
    keywords: [
      "certificado de reciclaje",
      "certificado de valorización",
      "certificado de disposición de residuos",
      "certificado ambiental empresa Chile",
      "qué es un certificado de reciclaje",
      "certificado reciclaje digital",
      "certificado de reciclaje para empresas",
      "certificado de gestión de residuos",
      "para qué sirve certificado de reciclaje",
      "cómo obtener certificado de reciclaje",
      "certificado valorización residuos Chile",
      "certificado reciclaje auditoría",
      "comprobante reciclaje empresa",
      "documento reciclaje empresa Chile",
      "certificado reciclaje Ley REP",
    ],
    date: "2026-03-01",
    readingTime: 8,
    category: "Certificados",
  },
  {
    slug: "ley-rep-chile-guia-completa",
    title: "Ley REP en Chile: guía completa 2026 — qué exige y cómo cumplir",
    description:
      "Todo sobre la Ley REP (20.920): plazos 2026, metas de reciclaje, productos prioritarios, multas, sistemas de gestión y cómo cumplir si eres gestora, generador o productor de residuos en Chile.",
    keywords: [
      "ley REP Chile",
      "ley 20920",
      "ley de reciclaje Chile",
      "responsabilidad extendida del productor",
      "metas reciclaje Chile 2026",
      "ley REP qué es",
      "ley REP productos prioritarios",
      "ley REP multas",
      "ley REP gestora",
      "ley REP obligaciones empresas",
      "ley REP envases y embalajes",
      "cómo cumplir ley REP",
      "sistema de gestión ley REP",
      "ley de fomento al reciclaje Chile",
      "ley 20920 resumen",
      "ley REP plazos 2026",
      "ley REP generador residuos",
    ],
    date: "2026-02-25",
    readingTime: 12,
    category: "Regulación",
  },
  {
    slug: "plan-gestion-residuos-empresa",
    title: "Plan de gestión de residuos en tu empresa: 5 pasos para implementarlo",
    description:
      "Aprende a crear un plan de gestión de residuos empresarial paso a paso: diagnóstico, clasificación, proveedores de reciclaje, trazabilidad digital y mejora continua. Guía práctica para Chile.",
    keywords: [
      "gestión de residuos empresas Chile",
      "plan de manejo de residuos",
      "gestión integral de residuos",
      "manejo de residuos industriales",
      "plan gestión residuos empresa",
      "cómo hacer plan de residuos",
      "plan de manejo de residuos empresa Chile",
      "gestión de residuos sólidos",
      "clasificación residuos empresa",
      "programa reciclaje empresa",
      "cómo reciclar en mi empresa",
      "residuos empresa paso a paso",
      "política de residuos empresa",
      "reducir residuos empresa",
      "reciclaje corporativo Chile",
      "manejo residuos pyme Chile",
    ],
    date: "2026-02-18",
    readingTime: 10,
    category: "Gestión",
  },
  {
    slug: "como-declarar-residuos-sinader",
    title: "Cómo declarar residuos en SINADER: guía paso a paso 2026",
    description:
      "Tutorial completo para declarar residuos en SINADER Chile: cómo ingresar, requisitos, plazos 2026, errores comunes, diferencia con RETC y tips para generadores y destinatarios.",
    keywords: [
      "SINADER Chile",
      "declaración de residuos SINADER",
      "RETC Chile",
      "ventanilla única RETC",
      "cómo declarar residuos",
      "SINADER tutorial",
      "SINADER paso a paso",
      "SINADER 2026",
      "declaración anual residuos Chile",
      "SINADER generador",
      "SINADER destinatario",
      "cómo ingresar a SINADER",
      "plazos declaración SINADER",
      "errores comunes SINADER",
      "declarar residuos no peligrosos",
      "sistema nacional declaración residuos",
      "RETC ventanilla única portal",
    ],
    date: "2026-02-10",
    readingTime: 9,
    category: "Regulación",
  },
  {
    slug: "economia-circular-chile-impacto-empresas",
    title: "Economía circular en Chile: cómo medir el impacto real de tu empresa",
    description:
      "Qué es la economía circular, cómo se aplica en empresas chilenas, indicadores para medir circularidad, hoja de ruta 2040 y herramientas para demostrar impacto ambiental concreto.",
    keywords: [
      "economía circular Chile",
      "economía circular empresas",
      "indicadores circularidad",
      "hoja de ruta economía circular Chile 2040",
      "qué es economía circular",
      "economía circular ejemplos Chile",
      "medir impacto ambiental empresa",
      "circularidad empresarial",
      "economía circular reciclaje",
      "economía circular beneficios empresa",
      "indicadores ambientales empresa",
      "impacto ambiental empresa Chile",
      "sustentabilidad empresarial Chile",
      "economía circular definición",
      "economía circular y ley REP",
      "economía circular residuos",
    ],
    date: "2026-02-03",
    readingTime: 10,
    category: "Sustentabilidad",
  },
  {
    slug: "co2-evitado-reciclaje-tabla-materiales",
    title: "Cuánto CO₂ evitas al reciclar: tabla completa por material [2026]",
    description:
      "Tabla de factores de emisión de CO₂ evitado por material reciclado: plástico PET, cartón, vidrio, aluminio, chatarra, papel y más. Fuentes GHG Protocol, IPCC y EPA WARM.",
    keywords: [
      "CO2 evitado reciclaje",
      "huella de carbono reciclaje",
      "factor emisión reciclaje",
      "calcular CO2 evitado",
      "GHG Protocol reciclaje",
      "tabla CO2 evitado por material",
      "cuánto CO2 se ahorra al reciclar",
      "factor de emisión por material reciclado",
      "CO2 evitado plástico PET",
      "CO2 evitado cartón",
      "CO2 evitado vidrio",
      "CO2 evitado aluminio",
      "emisiones evitadas reciclaje",
      "huella de carbono por material",
      "IPCC factores emisión reciclaje",
      "EPA WARM factores emisión",
      "kg CO2 por kg reciclado",
      "DEFRA factores emisión",
      "cuánto CO2 ahorro reciclando",
    ],
    date: "2026-01-28",
    readingTime: 7,
    category: "Huella de carbono",
  },
  {
    slug: "como-elegir-proveedor-reciclaje-chile",
    title: "Cómo elegir un proveedor de reciclaje confiable para tu empresa en Chile",
    description:
      "Criterios clave para elegir una gestora de reciclaje en Chile: certificaciones, trazabilidad, cobertura, precios, certificados de valorización y qué preguntar antes de contratar.",
    keywords: [
      "reciclaje empresas Chile",
      "proveedor reciclaje Santiago",
      "gestora de reciclaje Chile",
      "servicio reciclaje empresas",
      "retiro reciclaje empresas",
      "empresa de reciclaje Chile",
      "gestora de residuos Chile",
      "contratar reciclaje empresa",
      "reciclaje corporativo Chile",
      "empresa retiro residuos Santiago",
      "gestora reciclaje confiable",
      "reciclaje industrial Chile",
      "servicio retiro reciclaje",
      "cómo elegir gestora reciclaje",
      "reciclaje para empresas Santiago",
      "comparar gestoras reciclaje",
      "proveedor retiro residuos Chile",
    ],
    date: "2026-01-20",
    readingTime: 8,
    category: "Gestión",
  },
  {
    slug: "trazabilidad-residuos-digital-chile",
    title: "Trazabilidad digital de residuos en Chile: qué es y por qué será obligatoria",
    description:
      "Todo sobre trazabilidad de residuos en Chile: qué exige la Ley REP, beneficios de digitalizar, software de gestión de residuos y cómo implementar un sistema de seguimiento efectivo.",
    keywords: [
      "trazabilidad de residuos Chile",
      "trazabilidad residuos ley REP",
      "sistema gestión residuos software",
      "seguimiento residuos digital",
      "trazabilidad de residuos qué es",
      "software gestión residuos",
      "trazabilidad residuos obligatoria",
      "plataforma gestión residuos",
      "digitalización residuos Chile",
      "sistema seguimiento residuos",
      "tecnología reciclaje",
      "software reciclaje Chile",
      "gestión digital residuos",
      "trazabilidad cadena reciclaje",
      "control residuos digital",
      "plataforma reciclaje digital",
    ],
    date: "2026-01-13",
    readingTime: 9,
    category: "Tecnología",
  },
  {
    slug: "clasificacion-residuos-industriales-chile",
    title: "Clasificación de residuos industriales en Chile: guía práctica con normativa DS 148",
    description:
      "Guía para clasificar residuos industriales en Chile: peligrosos (RESPEL), no peligrosos, asimilables e inertes. Normativa DS 148, SIDREP, obligaciones legales y ejemplos por industria.",
    keywords: [
      "residuos industriales Chile",
      "clasificación residuos Chile",
      "RESPEL Chile",
      "residuos peligrosos empresas",
      "residuos no peligrosos",
      "tipos de residuos industriales",
      "clasificación residuos industriales",
      "RESPEL qué es",
      "DS 148 residuos peligrosos",
      "residuos peligrosos Chile normativa",
      "residuos asimilables",
      "residuos inertes Chile",
      "cómo clasificar residuos",
      "categorías residuos Chile",
      "SIDREP Chile",
      "manejo RESPEL empresa",
      "decreto supremo 148 Chile",
      "residuos peligrosos clasificación",
    ],
    date: "2026-01-06",
    readingTime: 11,
    category: "Regulación",
  },
  {
    slug: "cumplimiento-ambiental-certificados-reciclaje",
    title: "Cómo demostrar cumplimiento ambiental con certificados de reciclaje en Chile",
    description:
      "Usa certificados de reciclaje como evidencia en auditorías ISO 14001, reportes de sustentabilidad NCG 519, fiscalizaciones SMA, ESG y acuerdos de producción limpia en Chile.",
    keywords: [
      "cumplimiento ambiental Chile",
      "ISO 14001 reciclaje",
      "auditoría ambiental empresas",
      "sustentabilidad empresarial Chile",
      "reporte sostenibilidad",
      "certificados reciclaje auditoría",
      "cumplimiento ambiental empresa",
      "auditoría ISO 14001 Chile",
      "reporte sustentabilidad Chile",
      "NCG 519 reporte ambiental",
      "acuerdo producción limpia Chile",
      "fiscalización ambiental Chile",
      "SMA fiscalización ambiental",
      "ESG reciclaje Chile",
      "demostrar cumplimiento ambiental",
      "evidencia ambiental empresa",
      "certificado ambiental auditoría ISO",
    ],
    date: "2025-12-30",
    readingTime: 9,
    category: "Sustentabilidad",
  },
];

export function getArticleBySlug(slug: string): BlogArticle | undefined {
  return blogArticles.find((a) => a.slug === slug);
}
