export interface BlogArticle {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  date: string; // ISO date
  updatedDate?: string; // ISO date — última actualización
  readingTime: number; // minutes
  category: string;
  image?: string;
}

export const blogArticles: BlogArticle[] = [
  {
    slug: "que-es-certificado-de-reciclaje",
    title: "Qué es un certificado de reciclaje y por qué tu empresa lo necesita en 2026",
    description:
      "Guía completa sobre el certificado de reciclaje en Chile: qué es, qué datos debe contener, para qué sirve en auditorías ambientales, ISO 14001 y Ley REP, y cómo obtenerlo de forma digital.",
    keywords: [
      "certificado de reciclaje",
      "certificado de valorización",
      "certificado de disposición de residuos",
      "certificado ambiental empresa Chile",
      "qué es un certificado de reciclaje",
      "certificado reciclaje digital",
      "certificado de reciclaje para empresas",
      "certificado de gestión de residuos",
      "para qué sirve certificado de reciclaje",
      "cómo obtener certificado de reciclaje",
      "certificado valorización residuos Chile",
      "certificado reciclaje auditoría",
      "comprobante reciclaje empresa",
      "documento reciclaje empresa Chile",
      "certificado reciclaje Ley REP",
    ],
    date: "2026-03-01",
    updatedDate: "2026-03-12",
    readingTime: 8,
    category: "Certificados",
  },
  {
    slug: "ley-rep-chile-guia-completa",
    title: "Ley REP en Chile: guía completa 2026 — qué exige y cómo cumplir",
    description:
      "Todo sobre la Ley REP (20.920): plazos 2026, metas de reciclaje, productos prioritarios, multas, sistemas de gestión y cómo cumplir si eres gestora, generador o productor de residuos en Chile.",
    keywords: [
      "ley REP Chile",
      "ley 20920",
      "ley de reciclaje Chile",
      "responsabilidad extendida del productor",
      "metas reciclaje Chile 2026",
      "ley REP qué es",
      "ley REP productos prioritarios",
      "ley REP multas",
      "ley REP gestora",
      "ley REP obligaciones empresas",
      "ley REP envases y embalajes",
      "cómo cumplir ley REP",
      "sistema de gestión ley REP",
      "ley de fomento al reciclaje Chile",
      "ley 20920 resumen",
      "ley REP plazos 2026",
      "ley REP generador residuos",
    ],
    date: "2026-02-25",
    updatedDate: "2026-03-12",
    readingTime: 12,
    category: "Regulación",
  },
  {
    slug: "plan-gestion-residuos-empresa",
    title: "Plan de gestión de residuos en tu empresa: 5 pasos para implementarlo",
    description:
      "Aprende a crear un plan de gestión de residuos empresarial paso a paso: diagnóstico, clasificación, proveedores de reciclaje, trazabilidad digital y mejora continua. Guía práctica para Chile.",
    keywords: [
      "gestión de residuos empresas Chile",
      "plan de manejo de residuos",
      "gestión integral de residuos",
      "manejo de residuos industriales",
      "plan gestión residuos empresa",
      "cómo hacer plan de residuos",
      "plan de manejo de residuos empresa Chile",
      "gestión de residuos sólidos",
      "clasificación residuos empresa",
      "programa reciclaje empresa",
      "cómo reciclar en mi empresa",
      "residuos empresa paso a paso",
      "política de residuos empresa",
      "reducir residuos empresa",
      "reciclaje corporativo Chile",
      "manejo residuos pyme Chile",
    ],
    date: "2026-02-18",
    updatedDate: "2026-03-12",
    readingTime: 10,
    category: "Gestión",
  },
  {
    slug: "como-declarar-residuos-sinader",
    title: "Cómo declarar residuos en SINADER: guía paso a paso 2026",
    description:
      "Tutorial completo para declarar residuos en SINADER Chile: cómo ingresar, requisitos, plazos 2026, errores comunes, diferencia con RETC y tips para generadores y destinatarios.",
    keywords: [
      "SINADER Chile",
      "declaración de residuos SINADER",
      "RETC Chile",
      "ventanilla única RETC",
      "cómo declarar residuos",
      "SINADER tutorial",
      "SINADER paso a paso",
      "SINADER 2026",
      "declaración anual residuos Chile",
      "SINADER generador",
      "SINADER destinatario",
      "cómo ingresar a SINADER",
      "plazos declaración SINADER",
      "errores comunes SINADER",
      "declarar residuos no peligrosos",
      "sistema nacional declaración residuos",
      "RETC ventanilla única portal",
    ],
    date: "2026-02-10",
    updatedDate: "2026-03-12",
    readingTime: 9,
    category: "Regulación",
  },
  {
    slug: "economia-circular-chile-impacto-empresas",
    title: "Economía circular en Chile: cómo medir el impacto real de tu empresa",
    description:
      "Qué es la economía circular, cómo se aplica en empresas chilenas, indicadores para medir circularidad, hoja de ruta 2040 y herramientas para demostrar impacto ambiental concreto.",
    keywords: [
      "economía circular Chile",
      "economía circular empresas",
      "indicadores circularidad",
      "hoja de ruta economía circular Chile 2040",
      "qué es economía circular",
      "economía circular ejemplos Chile",
      "medir impacto ambiental empresa",
      "circularidad empresarial",
      "economía circular reciclaje",
      "economía circular beneficios empresa",
      "indicadores ambientales empresa",
      "impacto ambiental empresa Chile",
      "sustentabilidad empresarial Chile",
      "economía circular definición",
      "economía circular y ley REP",
      "economía circular residuos",
    ],
    date: "2026-02-03",
    updatedDate: "2026-03-12",
    readingTime: 10,
    category: "Sustentabilidad",
  },
  {
    slug: "co2-evitado-reciclaje-tabla-materiales",
    title: "Cuánto CO₂ evitas al reciclar: tabla completa por material [2026]",
    description:
      "Tabla de factores de emisión de CO₂ evitado por material reciclado: plástico PET, cartón, vidrio, aluminio, chatarra, papel y más. Fuentes GHG Protocol, IPCC y EPA WARM.",
    keywords: [
      "CO2 evitado reciclaje",
      "huella de carbono reciclaje",
      "factor emisión reciclaje",
      "calcular CO2 evitado",
      "GHG Protocol reciclaje",
      "tabla CO2 evitado por material",
      "cuánto CO2 se ahorra al reciclar",
      "factor de emisión por material reciclado",
      "CO2 evitado plástico PET",
      "CO2 evitado cartón",
      "CO2 evitado vidrio",
      "CO2 evitado aluminio",
      "emisiones evitadas reciclaje",
      "huella de carbono por material",
      "IPCC factores emisión reciclaje",
      "EPA WARM factores emisión",
      "kg CO2 por kg reciclado",
      "DEFRA factores emisión",
      "cuánto CO2 ahorro reciclando",
    ],
    date: "2026-01-28",
    updatedDate: "2026-03-12",
    readingTime: 7,
    category: "Huella de carbono",
  },
  {
    slug: "como-elegir-proveedor-reciclaje-chile",
    title: "Cómo elegir un proveedor de reciclaje confiable para tu empresa en Chile",
    description:
      "Criterios clave para elegir una gestora de reciclaje en Chile: certificaciones, trazabilidad, cobertura, precios, certificados de valorización y qué preguntar antes de contratar.",
    keywords: [
      "reciclaje empresas Chile",
      "proveedor reciclaje Santiago",
      "gestora de reciclaje Chile",
      "servicio reciclaje empresas",
      "retiro reciclaje empresas",
      "empresa de reciclaje Chile",
      "gestora de residuos Chile",
      "contratar reciclaje empresa",
      "reciclaje corporativo Chile",
      "empresa retiro residuos Santiago",
      "gestora reciclaje confiable",
      "reciclaje industrial Chile",
      "servicio retiro reciclaje",
      "cómo elegir gestora reciclaje",
      "reciclaje para empresas Santiago",
      "comparar gestoras reciclaje",
      "proveedor retiro residuos Chile",
    ],
    date: "2026-01-20",
    updatedDate: "2026-03-12",
    readingTime: 8,
    category: "Gestión",
  },
  {
    slug: "trazabilidad-residuos-digital-chile",
    title: "Trazabilidad digital de residuos en Chile: qué es y por qué será obligatoria",
    description:
      "Todo sobre trazabilidad de residuos en Chile: qué exige la Ley REP, beneficios de digitalizar, software de gestión de residuos y cómo implementar un sistema de seguimiento efectivo.",
    keywords: [
      "trazabilidad de residuos Chile",
      "trazabilidad residuos ley REP",
      "sistema gestión residuos software",
      "seguimiento residuos digital",
      "trazabilidad de residuos qué es",
      "software gestión residuos",
      "trazabilidad residuos obligatoria",
      "plataforma gestión residuos",
      "digitalización residuos Chile",
      "sistema seguimiento residuos",
      "tecnología reciclaje",
      "software reciclaje Chile",
      "gestión digital residuos",
      "trazabilidad cadena reciclaje",
      "control residuos digital",
      "plataforma reciclaje digital",
    ],
    date: "2026-01-13",
    updatedDate: "2026-03-12",
    readingTime: 9,
    category: "Tecnología",
  },
  {
    slug: "clasificacion-residuos-industriales-chile",
    title: "Clasificación de residuos industriales en Chile: guía práctica con normativa DS 148",
    description:
      "Guía para clasificar residuos industriales en Chile: peligrosos (RESPEL), no peligrosos, asimilables e inertes. Normativa DS 148, SIDREP, obligaciones legales y ejemplos por industria.",
    keywords: [
      "residuos industriales Chile",
      "clasificación residuos Chile",
      "RESPEL Chile",
      "residuos peligrosos empresas",
      "residuos no peligrosos",
      "tipos de residuos industriales",
      "clasificación residuos industriales",
      "RESPEL qué es",
      "DS 148 residuos peligrosos",
      "residuos peligrosos Chile normativa",
      "residuos asimilables",
      "residuos inertes Chile",
      "cómo clasificar residuos",
      "categorías residuos Chile",
      "SIDREP Chile",
      "manejo RESPEL empresa",
      "decreto supremo 148 Chile",
      "residuos peligrosos clasificación",
    ],
    date: "2026-01-06",
    updatedDate: "2026-03-12",
    readingTime: 11,
    category: "Regulación",
  },
  {
    slug: "cumplimiento-ambiental-certificados-reciclaje",
    title: "Cómo demostrar cumplimiento ambiental con certificados de reciclaje en Chile",
    description:
      "Usa certificados de reciclaje como evidencia en auditorías ISO 14001, reportes de sustentabilidad NCG 519, fiscalizaciones SMA, ESG y acuerdos de producción limpia en Chile.",
    keywords: [
      "cumplimiento ambiental Chile",
      "ISO 14001 reciclaje",
      "auditoría ambiental empresas",
      "sustentabilidad empresarial Chile",
      "reporte sostenibilidad",
      "certificados reciclaje auditoría",
      "cumplimiento ambiental empresa",
      "auditoría ISO 14001 Chile",
      "reporte sustentabilidad Chile",
      "NCG 519 reporte ambiental",
      "acuerdo producción limpia Chile",
      "fiscalización ambiental Chile",
      "SMA fiscalización ambiental",
      "ESG reciclaje Chile",
      "demostrar cumplimiento ambiental",
      "evidencia ambiental empresa",
      "certificado ambiental auditoría ISO",
    ],
    date: "2025-12-30",
    updatedDate: "2026-03-12",
    readingTime: 9,
    category: "Sustentabilidad",
  },
  // ---- Nuevos artículos Marzo 2026 (batch 3) ----
  {
    slug: "reducir-costos-gestion-residuos-empresa",
    title: "Cómo reducir costos en la gestión de residuos de tu empresa en Chile",
    description:
      "Guía práctica para reducir costos de gestión de residuos: segregación en origen, elección de proveedores, trazabilidad digital, reciclaje vs relleno sanitario y cálculos de ROI con ejemplos reales.",
    keywords: [
      "reducir costos residuos empresa",
      "ahorro gestión residuos",
      "costos reciclaje empresa Chile",
      "reducir gastos residuos",
      "ahorro reciclaje empresa",
      "costos disposición relleno sanitario",
      "ROI gestión residuos",
      "optimizar costos residuos",
      "segregación residuos ahorro",
      "costos gestión residuos Chile",
      "reducir costos relleno sanitario",
      "ahorro reciclaje vs relleno",
      "gestión residuos económica",
      "costo disposición residuos Chile",
    ],
    date: "2026-03-13",
    readingTime: 11,
    category: "Gestión",
  },
  {
    slug: "puntos-limpios-chile-donde-reciclar",
    title: "Puntos limpios en Chile: qué son, dónde encontrarlos y cómo funcionan [2026]",
    description:
      "Guía completa de puntos limpios en Chile: qué son, qué materiales aceptan, dónde encontrarlos, principales redes municipales y privadas, y diferencias con el reciclaje corporativo profesional.",
    keywords: [
      "puntos limpios Chile",
      "dónde reciclar Chile",
      "puntos de reciclaje Santiago",
      "punto limpio cerca de mí",
      "puntos limpios Santiago",
      "dónde reciclar Santiago",
      "punto limpio qué es",
      "puntos de reciclaje Chile",
      "mapa puntos limpios Chile",
      "reciclaje puntos limpios",
      "dónde llevar reciclaje Santiago",
      "puntos limpios municipales",
      "centros de reciclaje Chile",
      "puntos verdes reciclaje Chile",
    ],
    date: "2026-03-13",
    readingTime: 10,
    category: "Sustentabilidad",
  },
  // ---- Nuevos artículos Marzo 2026 (batch 2) ----
  {
    slug: "reciclaje-residuos-construccion-demolicion-chile",
    title: "Reciclaje de residuos de construcción y demolición (RCD) en Chile: normativa y oportunidades",
    description:
      "Guía completa sobre residuos de construcción y demolición en Chile: tipos de RCD, normativa DS 148 y Ley REP, oportunidades de reciclaje de hormigón, metales y madera, y cómo implementar trazabilidad en obras.",
    keywords: [
      "residuos construcción demolición Chile",
      "reciclaje RCD Chile",
      "residuos obra Chile",
      "residuos construcción Chile",
      "escombros reciclaje Chile",
      "árido reciclado Chile",
      "gestión RCD Chile",
      "reciclaje hormigón Chile",
      "residuos demolición normativa",
      "NCh 3562 RCD",
      "plan gestión RCD",
      "reciclaje madera construcción",
      "chatarra construcción reciclaje",
      "drywall reciclaje Chile",
    ],
    date: "2026-03-13",
    readingTime: 11,
    category: "Industria",
  },
  {
    slug: "compostaje-industrial-chile-guia",
    title: "Compostaje industrial en Chile: cómo implementarlo y cumplir la normativa",
    description:
      "Guía práctica de compostaje industrial en Chile: proceso, normativa NCh 2880 y DS 594, tipos de residuos orgánicos, costos de implementación, beneficios de CO₂ evitado y pasos para empresas.",
    keywords: [
      "compostaje industrial Chile",
      "compostaje empresarial",
      "residuos orgánicos empresa Chile",
      "compostaje gran escala Chile",
      "planta compostaje Chile",
      "compostaje normativa Chile",
      "NCh 2880 compost",
      "residuos orgánicos valorización",
      "compostaje aeróbico industrial",
      "costo compostaje industrial",
      "desvío vertedero orgánicos",
      "CO2 evitado compostaje",
      "compostaje industria alimentaria",
      "compost mejorador suelos Chile",
    ],
    date: "2026-03-13",
    readingTime: 12,
    category: "Gestión",
  },
  // ---- Nuevos artículos Marzo 2026 ----
  {
    slug: "reportes-sustentabilidad-ncg-461-empresas-chile",
    title: "Reportes de sustentabilidad en Chile: NCG 461, estándares y cómo prepararse",
    description:
      "Guía sobre reportes de sustentabilidad en Chile: qué exige la NCG 461 de la CMF, estándares IFRS S1/S2 y GRI, qué datos de residuos y reciclaje incluir, y cómo los certificados de reciclaje sirven como evidencia ESG.",
    keywords: [
      "reportes sustentabilidad Chile",
      "NCG 461 Chile",
      "reporte ESG reciclaje",
      "informe sustentabilidad empresa Chile",
      "NCG 461 CMF",
      "IFRS S1 S2 Chile",
      "GRI 306 residuos",
      "reporte sustentabilidad obligatorio",
      "ESG residuos Chile",
      "reporte ambiental empresa",
      "sustentabilidad empresarial Chile",
      "indicadores ESG reciclaje",
      "verificación reporte sustentabilidad",
      "datos ambientales reporte ESG",
    ],
    date: "2026-03-13",
    readingTime: 12,
    category: "Sustentabilidad",
  },
  {
    slug: "reciclaje-residuos-electronicos-raee-chile",
    title: "Reciclaje de residuos electrónicos (RAEE) en Chile: normativa y gestión empresarial",
    description:
      "Guía de gestión de RAEE en Chile para empresas: tipos de residuos electrónicos, Ley REP para AEE, DS 148, destrucción segura de datos, gestores certificados y programas corporativos de reciclaje electrónico.",
    keywords: [
      "residuos electrónicos Chile",
      "RAEE Chile",
      "reciclaje electrónicos empresa",
      "ley REP electrónicos",
      "RAEE ley REP",
      "residuos electrónicos empresa",
      "reciclaje RAEE Chile",
      "gestión RAEE empresas",
      "destrucción datos equipos",
      "reciclaje computadores Chile",
      "residuos aparatos electrónicos",
      "e-waste Chile",
      "gestor RAEE certificado",
      "reciclaje equipos electrónicos empresa",
    ],
    date: "2026-03-12",
    readingTime: 11,
    category: "Industria",
  },
  {
    slug: "certificacion-iso-14001-reciclaje-chile",
    title: "Certificación ISO 14001 y reciclaje en Chile: guía paso a paso para empresas",
    description:
      "Guía paso a paso para integrar la gestión de reciclaje en un Sistema de Gestión Ambiental ISO 14001: requisitos documentales, certificados de reciclaje para auditorías, integración con Ley REP y mejora continua.",
    keywords: [
      "ISO 14001 reciclaje Chile",
      "certificación ISO 14001 Chile",
      "sistema gestión ambiental reciclaje",
      "auditoría ISO 14001 residuos",
      "ISO 14001 gestión residuos",
      "SGA reciclaje Chile",
      "certificación ambiental empresa Chile",
      "ISO 14001 Ley REP",
      "auditoría ambiental reciclaje",
      "mejora continua reciclaje",
      "ISO 14001 certificados reciclaje",
      "sistema gestión ambiental Chile",
      "ISO 14001 paso a paso",
      "requisitos ISO 14001 residuos",
    ],
    date: "2026-03-13",
    readingTime: 12,
    category: "Regulación",
  },
  {
    slug: "logistica-reversa-reciclaje-implementar-chile",
    title: "Logística reversa en Chile: qué es y cómo implementarla para reciclaje",
    description:
      "Guía práctica de logística reversa para reciclaje en Chile: definición, marco Ley REP, modelos de recolección, pasos de implementación, costos, trazabilidad y factores de éxito.",
    keywords: [
      "logística reversa Chile",
      "logística reversa reciclaje",
      "cómo implementar logística reversa",
      "logística reversa Ley REP",
      "recolección residuos reciclaje Chile",
      "logística inversa Chile",
      "sistema recolección reciclaje",
      "logística reversa envases embalajes",
      "costos logística reversa",
      "modelos logística reversa",
      "trazabilidad logística reversa",
      "logística reversa empresas Chile",
      "recolección selectiva Chile",
      "logística reversa economía circular",
    ],
    date: "2026-03-13",
    readingTime: 11,
    category: "Gestión",
  },
  {
    slug: "manejo-residuos-peligrosos-respel-chile",
    title: "Manejo de residuos peligrosos (RESPEL) en Chile: guía completa DS 148",
    description:
      "Guía completa sobre el manejo de residuos peligrosos (RESPEL) en Chile: clasificación según DS 148, almacenamiento, transporte, manifiestos SIDREP, costos, sanciones y buenas prácticas para empresas.",
    keywords: [
      "residuos peligrosos Chile",
      "RESPEL Chile",
      "DS 148 Chile",
      "manejo RESPEL empresa",
      "decreto supremo 148",
      "residuos peligrosos DS 148",
      "SIDREP Chile",
      "manifiesto RESPEL",
      "almacenamiento RESPEL",
      "transporte residuos peligrosos Chile",
      "clasificación RESPEL",
      "plan manejo RESPEL",
      "sanciones RESPEL Chile",
      "relleno de seguridad Chile",
    ],
    date: "2026-03-11",
    readingTime: 12,
    category: "Regulación",
  },
  {
    slug: "reciclaje-sector-horeca-hoteles-restaurantes-chile",
    title: "Reciclaje en hoteles, restaurantes y catering (HORECA) en Chile: guía práctica",
    description:
      "Guía práctica de reciclaje y gestión de residuos en el sector HORECA en Chile: tipos de residuos, normativa, segregación en fuente, costos, certificaciones de sustentabilidad turística y documentación ambiental.",
    keywords: [
      "reciclaje hoteles Chile",
      "reciclaje restaurantes Chile",
      "residuos HORECA Chile",
      "reciclaje sector HORECA",
      "gestión residuos hoteles",
      "gestión residuos restaurantes",
      "residuos orgánicos restaurante",
      "reciclaje turismo Chile",
      "Sello S SERNATUR",
      "sustentabilidad hotelera Chile",
      "reciclaje catering Chile",
      "aceite usado restaurante",
      "segregación residuos cocina",
      "certificación sustentabilidad turística",
    ],
    date: "2026-03-11",
    readingTime: 11,
    category: "Industria",
  },
  {
    slug: "certirecicla-automatiza-cumplimiento-ley-rep",
    title: "Cómo CertiRecicla automatiza tu cumplimiento de la Ley REP en Chile",
    description:
      "Descubre cómo CertiRecicla digitaliza certificados de reciclaje, exporta a SINADER y automatiza la trazabilidad de residuos para cumplir la Ley REP sin planillas ni errores manuales.",
    keywords: [
      "CertiRecicla",
      "software reciclaje Chile",
      "plataforma gestión residuos",
      "automatizar ley REP",
      "software gestora reciclaje",
      "certificados reciclaje automáticos",
      "exportar SINADER automático",
      "plataforma reciclaje Chile",
      "software certificados reciclaje",
      "digitalizar gestión residuos",
      "automatizar certificados reciclaje",
      "software cumplimiento ley REP",
      "plataforma gestora residuos Chile",
      "sistema gestión residuos online",
    ],
    date: "2026-03-10",
    readingTime: 10,
    category: "Producto",
  },
  {
    slug: "multas-ley-rep-chile-casos-reales",
    title: "Multas de la Ley REP en Chile: montos, casos y cómo evitarlas [2026]",
    description:
      "Guía sobre multas y sanciones de la Ley REP (20.920) en Chile: tipos de infracciones, montos de hasta 10.000 UTA, fiscalización SMA, casos reales y 7 pasos para evitar sanciones.",
    keywords: [
      "multas ley REP Chile",
      "sanciones ley REP",
      "fiscalización ambiental Chile",
      "SMA multas reciclaje",
      "infracciones ley 20920",
      "multas ley REP montos",
      "fiscalización SMA Chile",
      "sanciones ambientales Chile",
      "multas ambientales empresas Chile",
      "cómo evitar multas ley REP",
      "infracciones ambientales Chile",
      "superintendencia medio ambiente multas",
      "ley REP penalidades",
      "multas reciclaje Chile",
    ],
    date: "2026-03-08",
    readingTime: 11,
    category: "Regulación",
  },
  {
    slug: "reciclaje-industria-minera-chile",
    title: "Reciclaje en la industria minera en Chile: normativa, residuos y oportunidades",
    description:
      "Guía de reciclaje y gestión de residuos en minería chilena: tipos de residuos mineros, normativa DS 148 y Ley REP, oportunidades de valorización y cómo implementar trazabilidad en faenas.",
    keywords: [
      "reciclaje minería Chile",
      "residuos mineros Chile",
      "gestión residuos minería",
      "neumáticos OTR reciclaje",
      "RESPEL minería Chile",
      "reciclaje industrial minería",
      "residuos peligrosos minería",
      "chatarra minería reciclaje",
      "aceites usados minería",
      "ley REP minería",
      "valorización residuos mineros",
      "gestión ambiental minería Chile",
      "reciclaje faenas mineras",
      "DS 148 minería",
    ],
    date: "2026-03-06",
    readingTime: 10,
    category: "Industria",
  },
  {
    slug: "reciclaje-retail-supermercados-chile",
    title: "Reciclaje en retail y supermercados en Chile: cómo cumplir la Ley REP",
    description:
      "Cómo gestionar residuos en retail y supermercados en Chile: Ley REP para envases y embalajes, metas de reciclaje, buenas prácticas de segregación y certificados para reportes ESG.",
    keywords: [
      "reciclaje retail Chile",
      "reciclaje supermercados Chile",
      "ley REP envases embalajes",
      "cartón reciclaje retail",
      "residuos supermercado Chile",
      "reciclaje envases Chile",
      "gestión residuos retail",
      "ley REP comercio",
      "reciclaje plástico retail",
      "metas reciclaje envases Chile",
      "ESG retail Chile",
      "sustentabilidad supermercados",
      "residuos envases embalajes Chile",
      "reciclaje cadena retail",
    ],
    date: "2026-03-04",
    readingTime: 9,
    category: "Industria",
  },
  {
    slug: "reciclaje-industria-alimentaria-chile",
    title: "Reciclaje en la industria alimentaria en Chile: residuos, normativa y soluciones",
    description:
      "Guía de gestión de residuos en la industria de alimentos en Chile: residuos orgánicos, envases, RESPEL, normativa sanitaria, valorización y certificados para auditorías BRC y FSSC 22000.",
    keywords: [
      "reciclaje industria alimentaria Chile",
      "residuos orgánicos empresa Chile",
      "ley REP alimentos",
      "gestión residuos alimentos",
      "reciclaje envases alimentos",
      "residuos industria alimentos",
      "compostaje industrial Chile",
      "valorización residuos orgánicos",
      "RESPEL industria alimentaria",
      "BRC gestión residuos",
      "FSSC 22000 residuos",
      "reciclaje planta alimentos",
      "residuos orgánicos valorización",
      "sustentabilidad industria alimentos Chile",
    ],
    date: "2026-03-02",
    readingTime: 10,
    category: "Industria",
  },
];

export function getArticleBySlug(slug: string): BlogArticle | undefined {
  return blogArticles.find((a) => a.slug === slug);
}
